name: Build PROD image, push and DEMO deployment

on:
  workflow_call:

jobs:
  announce:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Announce Release on Slack
        run: 'echo "Official Plugin for Slack Available: https://github.com/marketplace/actions/slack-send"'

      - name: Announce Release on Teams
        run: 'echo "Teams: Call the Webhook...."'

