# Reusable workflow to deploy an image to a k8s environment
name: deploy

on:
  workflow_call:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all # automated release via api needs many permissions
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine tag
        run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"


      - name: DEMO Alter deployment config and apply it in Kubernetes...
        id: task-def
        run: |
          echo "# get kubeconfig for this context..."
          echo "kubectl config use-context ..."
          echo "# manage namespace"
          echo "kubectl create namespace $NAMESPACE_SLUG --dry-run=client -o yaml | kubectl apply -f -"
          echo "export DOCKER_IMAGE_TAG=$CI_COMMIT_SHORT_SHA"
          echo "# apply the deployment"
          echo "cat ./deployment/develop.yaml | envsubst | kubectl apply -f -"

      - name: Create release
        uses: "actions/github-script@v6"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.RELEASE_TAG,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
              });
            
              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }

  # Announce to external messenger services using a reusable workflow call in this job
  announce-prod:
    needs: deploy
    uses: ./.github/workflows/announce.yml
    secrets: inherit


